apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-deployment1
  labels:
    app: deployment1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-deployment1
  template:
    metadata:
      labels:
        app: pod-deployment1
    spec:
      containers:
      - name: container-deployment1
        image: makbar4721/assignment4
        ports:
        - containerPort: 8006

---

apiVersion: v1
kind: Service
metadata:
  name: docker-service1
  labels:
    app: deployment1
spec:
  selector:
    app: pod-deployment1
  ports:
    - protocol: TCP
      port: 8006
      targetPort: 8000
  type: ClusterIP

