apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-deployment3 
  labels: 
    app: deployment3

spec:
  replicas: 1
  selector:   
    matchLabels: 
      app: pod-deployment3 
  template: 
    metadata:
      labels: 
        app: pod-deployment3 
    spec: 
      containers:
      - name: container-deployment3 
        image: makbar4721/assignment4 
        ports: 
        - containerPort: 8008 

--- 

apiVersion: v1 
kind: Service 
metadata: 
  name: docker-service3 
  labels: 
    app: docker-service3 
spec: 
  selector: 
    app: pod-deployment3
  ports: 
    - protocol: TCP 
      port: 8008 
      targetPort: 8000 
  type: LoadBalancer   





    
  